# Generated by Django 5.1 on 2024-08-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0002_remove_book_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.FloatField(),
        ),
    ]
