# Generated by Django 5.1 on 2024-08-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0003_alter_book_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
