# Generated by Django 5.1 on 2024-08-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0004_alter_book_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="title",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
    ]
