# Generated by Django 5.1 on 2024-08-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0005_book_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
