# Generated by Django 5.1 on 2024-08-25 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0007_book_cover_book_created_at_book_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn_10", models.CharField(blank=True, max_length=10)),
                ("isbn_13", models.CharField(blank=True, max_length=13)),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="number",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="demo.booknumber",
            ),
        ),
    ]
